# Задание 1.3.1

Условие

```
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами
```



In [1]:
import numpy as np

a = []
for i in range(8):
  for j in range(8):
    a.append((i + j + 1) % 2)

res = np.array(a).reshape(8,8 )
print(res)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Задание 1.3.2

Условие


```
# Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange
```



In [ ]:
arr = np.arange(25).reshape(5, 5)
for i in range(1, 5):
    arr[i] = arr[0]

print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Задание 1.3.3

Условие

```
# Создать массив 3x3x3 со случайными значениями.
```



In [ ]:
import numpy as np
rand = np.random.random((3,3,3))
print(rand)

[[[0.29483924 0.41226301 0.3330816 ]
  [0.58996702 0.13283541 0.548384  ]
  [0.48391433 0.33991468 0.94496367]]

 [[0.90649825 0.76240429 0.17912073]
  [0.88112351 0.96744211 0.41638798]
  [0.60877006 0.46460841 0.11539952]]

 [[0.83879129 0.87620482 0.73101336]
  [0.62518098 0.96209195 0.32687752]
  [0.11244152 0.22880654 0.69833322]]]


# Задание 1.3.4


Условие

```
Создать матрицу с 0 внутри, и 1 на границах
```



In [ ]:
n = int(input("Введите размер матрицы: "))
a = np.full(n*n, 0).reshape(n, n)

for i in range(n):
  for j in range(n):
    if(i == 0 or i == n - 1 or j == 0 or j == n - 1):
      a[i][j] = 1

print(a)

Введите размер матрицы: 6
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


# Задание 1.3.5

Условие


```
#Создайте массив и отсортируйте его по убыванию.
```



In [ ]:
arr = np.random.random(10)
print(np.sort(arr)[::-1])

[0.91830347 0.76605557 0.70693554 0.64297109 0.64186413 0.6319278
 0.40542187 0.37060139 0.3181018  0.10656474]


# Задание 1.3.6


Условие


```
Создайте матрицу, выведите ее форму, размер и размерность.
```



In [ ]:
arr = np.random.random((3, 3, 3))
print("Форма: ", arr.shape)
print("Размер: ", arr.size)
print("Размерность: ", arr.ndim)


Форма:  (3, 3, 3)
Размер:  27
Размерность:  3


# Задание 2.3.1







Условие


```
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.
```


In [ ]:
import pandas as pd
import numpy as np

rng = np.random.default_rng()


a = pd.Series(rng.integers(1, 10, 5))
b = pd.Series(rng.integers(1, 10, 5))
print(sum((a-b)**2)**0.5)

3.872983346207417


# Задание 2.3.2

Условие



```
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).
```



In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'

dataframe = pd.read_csv(url)
dataframe

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
0    0.271  0.328   74  161  22  6  12   58  49  133  23  17   1   1   0   0   
1    0.264  0.318   24   48   7  0   1   22  15   18   0   7   0   0   0   0   
2    0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
3    0.224  0.274   28   94  21  1   1   44  27   54   2   7   1   1   0   0   
4    0.206  0.262   14   51  18  1   1   28  17   26   0   3   1   1   0   0   
..     ...    ...  ...  ...  .. ..  ..  ...  ..  ...  ..  ..  ..  ..  ..  ..   
332  0.269  0.303   32   58  12  1  13   33  11   51   1   2   0   0   0   0   
333  0.288  0.366   24   47   7  0   7   24  18   23   2   3   0   0   0   0   
334  0.208  0.265   12   35  11  1   0   15  14   30   2   6   0   0   0   0   
335  0.290  0.349   59  141  30  2  16   64  42  102  14   6   1   0   0   0   
336  0.225  0.312   37   64  12  0  17   48  36   80   1   0   1   0   0   0   

     salary  
0       109  
1       160  
2      2700  
3       550  
4       300  
..      ...  
332     140  
333     525  
334     365  
335     990  
336    2167  

[337 rows x 17 columns]

# Задание 2.3.3

Условие


```
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.
```



In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'

dataframe = pd.read_csv(url)

dataframe.head(3)
dataframe.tail(2)
dataframe.shape
dataframe.describe()



1           2           3           4           5           6  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     0.257825    0.323973   46.697329   92.833828   16.673591    2.338279   
std      0.039546    0.047132   29.020166   51.896322   10.452001    2.543336   
min      0.063000    0.063000    0.000000    1.000000    0.000000    0.000000   
25%      0.238000    0.297000   22.000000   51.000000    9.000000    0.000000   
50%      0.260000    0.323000   41.000000   91.000000   15.000000    2.000000   
75%      0.281000    0.354000   69.000000  136.000000   23.000000    3.000000   
max      0.457000    0.486000  133.000000  216.000000   49.000000   15.000000   

                7           8           9          10          11          12  \
count  337.000000  337.000000  337.000000  337.000000  337.000000  337.000000   
mean     9.097923   44.020772   35.017804   56.706231    8.246291    6.771513   
std      9.289934   29.559406   24.842474   33.828784   11.664782    5.927490   
min      0.000000    0.000000    0.000000    1.000000    0.000000    0.000000   
25%      2.000000   21.000000   15.000000   31.000000    1.000000    3.000000   
50%      6.000000   39.000000   30.000000   49.000000    4.000000    5.000000   
75%     15.000000   66.000000   49.000000   78.000000   11.000000    9.000000   
max     44.000000  133.000000  138.000000  175.000000   76.000000   31.000000   

               13          14          15          16       salary  
count  337.000000  337.000000  337.000000  337.000000   337.000000  
mean     0.397626    0.115727    0.192878    0.029674  1248.528190  
std      0.490135    0.320373    0.395145    0.169938  1240.013309  
min      0.000000    0.000000    0.000000    0.000000   109.000000  
25%      0.000000    0.000000    0.000000    0.000000   230.000000  
50%      0.000000    0.000000    0.000000    0.000000   740.000000  
75%      1.000000    0.000000    0.000000    0.000000  2150.000000  
max      1.000000    1.000000    1.000000    1.000000  6100.000000

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'

dataframe = pd.read_csv(url)

dataframe.iloc[3:8]

1      2   3    4   5  6   7   8   9   10  11  12  13  14  15  16  \
3  0.224  0.274  28   94  21  1   1  44  27   54   2   7   1   1   0   0   
4  0.206  0.262  14   51  18  1   1  28  17   26   0   3   1   1   0   0   
5  0.238  0.272  53  106  18  3  15  59  22  107  14   7   0   0   0   0   
6  0.115  0.148   0    3   1  0   0   2   1    6   0   3   0   0   0   0   
7  0.307  0.405  98  167  35  1  14  52  84   72   0  15   0   0   0   0   

   salary  
3     550  
4     300  
5     230  
6     109  
7     560

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baseball.csv'

dataframe = pd.read_csv(url)

dataframe[dataframe['salary'] == 2700].head(2)

1      2    3    4   5  6   7    8   9   10  11  12  13  14  15  16  \
2    0.251  0.338  101  141  35  3  32  105  71  104  34   6   0   0   1   0   
173  0.246  0.293   58  144  22  1  18   66  33  104   5  17   1   0   0   0   

     salary  
2      2700  
173    2700

# Задание 3.3.2

Условие


```
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.
```



In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe = pd.read_csv(url)

s1 = MinMaxScaler()
s2 = StandardScaler()

dataframe[['sepal_length_cm']] = s1.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = s2.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]